config/routes.rb
Rails.application.routes.draw do


  resources :responsibilities
  resources :setups
  resources :sorts
  resources :sort_types
  resources :rosters
  devise_for :users
  resources :schedules
  resources :team_members
  resources :positions

  root to: "home#index"

  get '/dashboard', to: "home#dashboard", as: 'dashboard'
  get '/employees', to: "team_members#index", as: 'employees'

  get "/add_dates_unavailable/", to: 'team_members#add_dates_unavailable', as: 'add_dates_unavailable'
  get "/remove_dates_unavailable/:id", to: 'team_members#remove_dates_unavailable', as: 'remove_dates_unavailable'

  get "/add_permanent_position", to: 'team_members#add_permanent_position', as: 'add_permanent_position'
  get "/remove_permanent_position/:id", to: 'team_members#remove_permanent_position', as: 'remove_permanent_position'

end

app/models/setup.rb
class Setup < ApplicationRecord
  has_and_belongs_to_many :positions
  has_many :sort_types
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  before_action :set_setup, only: [:show, :edit, :update, :destroy]

  # GET /setups
  # GET /setups.json
  def index
    @setups = Setup.all
  end

  # GET /setups/1
  # GET /setups/1.json
  def show
  end

  # GET /setups/new
  def new
    @user = current_user
    @positions = Position.all
    @setup = Setup.new
  end

  # GET /setups/1/edit
  def edit
    @user = current_user
    @positions = Position.all
  end

  # POST /setups
  # POST /setups.json
  def create
    @setup = Setup.new(setup_params)

    respond_to do |format|
      if @setup.save
        format.html { redirect_to @setup, notice: 'Setup was successfully created.' }
        format.json { render :show, status: :created, location: @setup }
      else
        format.html { render :new }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setups/1
  # PATCH/PUT /setups/1.json
  def update
    respond_to do |format|
      if @setup.update(setup_params)
        format.html { redirect_to @setup, notice: 'Setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @setup }
      else
        format.html { render :edit }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setups/1
  # DELETE /setups/1.json
  def destroy
    @setup.destroy
    respond_to do |format|
      format.html { redirect_to setups_url, notice: 'Setup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setup
      @setup = Setup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setup_params
      params.require(:setup).permit(
        :name,
        :user_id,
        :position_ids => []
      )
    end
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_form.html.erb
<%= form_for(setup) do |f| %>
  <% if setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setup.errors.count, "error") %> prohibited this setup from being saved:</h2>

      <ul>
      <% setup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name %><br /> 
    <%= f.collection_check_boxes :position_ids, @positions, :id, :name %>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/setups/edit.html.erb
<h1>Editing Setup</h1>

<%= render 'form', setup: @setup %>

<%= link_to 'Show', @setup %> |
<%= link_to 'Back', setups_path %>

app/views/setups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Setups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @setups.each do |setup| %>
      <tr>
        <td>Name: </td>
        <td><%= setup.name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', setup %></td>
        <td><%= link_to 'Edit', edit_setup_path(setup) %></td>
        <td><%= link_to 'Destroy', setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setup', new_setup_path %>

app/views/setups/new.html.erb
<h1>New Setup</h1>

<%= render 'form', setup: @setup %>

<%= link_to 'Back', setups_path %>

app/views/setups/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @setup.name %></h1>

<table>
  <tbody>
    <% @setup.positions.each do |position| %>
      <tr>
        <td>Name:</td>
        <td><%= position.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_setup_path(@setup) %> |
<%= link_to 'Back', setups_path %>