config/routes.rb
Rails.application.routes.draw do


  resources :responsibilities
  resources :setups
  resources :sorts
  resources :sort_types
  resources :rosters
  devise_for :users
  resources :schedules
  resources :team_members
  resources :positions

  root to: "home#index"

  get '/dashboard', to: "home#dashboard", as: 'dashboard'
  get '/employees', to: "team_members#index", as: 'employees'

  get "/add_dates_unavailable/", to: 'team_members#add_dates_unavailable', as: 'add_dates_unavailable'
  get "/remove_dates_unavailable/:id", to: 'team_members#remove_dates_unavailable', as: 'remove_dates_unavailable'

  get "/add_permanent_position", to: 'team_members#add_permanent_position', as: 'add_permanent_position'
  get "/remove_permanent_position/:id", to: 'team_members#remove_permanent_position', as: 'remove_permanent_position'

end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rosters
  has_many :responsibilities

  def full_name
    "#{first_name} #{last_name}"
  end

  def unavailable_start_date
    #Here as a method for form submission
  end

  def unavailable_end_date
    #Here as a method for form submission
  end

  def newbie?
    days = DateTime.now.mjd - self.date_of_hire.mjd
    days < 28
  end

end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    path = request.original_fullpath

    if path == "/employees"
      @team_members = TeamMember.all
    else
     @team_members = current_user.team_members
   end

  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @user = current_user
    @team_member = TeamMember.new(team_member_params)
    @team_member.dates_unavailable = dates_unavailable
    @team_member.permanent_positions = permanent_positions

    respond_to do |format|
      if @team_member.save

        @user.team_members << @team_member

        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params) && @team_member.update(
          dates_unavailable: dates_unavailable,
          permanent_positions: permanent_positions
        )

        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_dates_unavailable
    @team_member = TeamMember.new
    respond_to do |format|
      format.js
    end
  end

  def remove_dates_unavailable
    @id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  def add_permanent_position
    @team_member = TeamMember.new
    respond_to do |format|
      format.js
    end
  end

  def remove_permanent_position
    @id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      # params.fetch(:team_member, {})
      params.require(:team_member).permit(
        :first_name,
        :last_name,
        :employee_number,
        :date_of_hire,
        :extra,
        :light_duty
      )
    end

    def dates_unavailable
      dates = []

      get_ids.each do |id|
        sd = params.require(id).permit(
          :unavailable_start_date
        )

        ed = params.require(id).permit(
          :unavailable_end_date
        )

        unless sd.empty? || ed.empty?
          sd_year = sd["unavailable_start_date(1i)"]
          sd_month = sd["unavailable_start_date(2i)"]
          sd_day = sd["unavailable_start_date(3i)"]

          ed_year = ed["unavailable_end_date(1i)"]
          ed_month = ed["unavailable_end_date(2i)"]
          ed_day = ed["unavailable_end_date(3i)"]

          start_date = Date.parse("#{sd_year}/#{sd_month}/#{sd_day}")
          end_date = Date.parse("#{ed_year}/#{ed_month}/#{ed_day}")

          dates << [id, start_date, end_date]
        end
      end

      dates
    end

    def permanent_positions
      positions = []

      get_ids.each do |id|
        pp = params.require(id).permit(
          :position
        )

        st = params.require(id).permit(
          :sort_type
        )

        unless pp.empty? || st.empty?
          positions << [id, pp["position"], st["sort_type"]]
        end
      end

      positions
    end

    def get_ids
      ids = params.keys.select {|k| k.scan(/\D/).empty?}
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper

  def gen_id
    DateTime.now.to_i
  end

end

app/views/team_members/_dates_unavailable.html.erb
<% dates ||= [gen_id, DateTime.now.to_s, DateTime.now.to_s] %>
<div class="dates_unavailable" id="<%= dates[0] %>">

    <%= f.label :unavailable_start_date %><br />
    <%= f.date_select :unavailable_start_date, {:prefix => "#{dates[0]}", :default => Date.parse(dates[1])} %>
    <%= f.label :unavailable_end_date %><br />
    <%= f.date_select :unavailable_end_date, {:prefix => "#{dates[0]}", :default => Date.parse(dates[2])} %>

  <%= link_to "Remove", remove_dates_unavailable_path(dates[0]), :remote => true %>
</div>

app/views/team_members/_form.html.erb
<%= form_for(team_member) do |f| %>
  <% if team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% team_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_for @team_member do |f| %>
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
      <%= f.label :employee_number %><br />
      <%= f.text_field :employee_number %><br />
      <%= f.label :date_of_hire %><br />
      <%= f.date_select :date_of_hire %>
      <%= link_to "Add Dates Unavailable", add_dates_unavailable_path, :remote => true %>
      <div id="dates">
        <% team_member.dates_unavailable.each do |date_set| %>
          <%= render partial: "dates_unavailable", locals: { f: f, dates: date_set } %>
        <% end %>
      </div>
      <%= f.label :light_duty %><br />
      <%= f.check_box :light_duty %><br />
      <%= link_to "Add Permanent Position", add_permanent_position_path, :remote => true %>
      <div id="permanent-positions">
        <% team_member.permanent_positions.each do |position_set| %>
          <%= render partial: "permanent_position", locals: { f: f, position: position_set } %>
        <% end %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>

app/views/team_members/_permanent_position.html.erb
<% position ||= [gen_id, "", ""] %>
<% id = position[0] %>

<div class="permanent_position" id="<%= id %>">

  <%= f.label :permanent_position %><br />
  <%= f.collection_select :permanent_positions, Position.all, :id, :name,
    {prompt: "Select a Position", selected: "#{position[1]}"},
    {name: "#{id}[position]"}
  %>

  <%= f.label :for_sort %>
  <%= f.collection_select :permanent_positions, SortType.all, :id, :name,
    {prompt: "Select a Sort Type", selected: "#{position[2]}"},
    {name: "#{id}[sort_type]"}
  %>

  <%= link_to "Remove", remove_permanent_position_path(id), :remote => true %>
</div>

app/views/team_members/add_dates_unavailable.js.erb
'<%= form_for(@team_member) do |ff| %>'
  $('#dates').append('<%= escape_javascript(render partial: "dates_unavailable", locals: { f: ff }) %>');
'<% end %>'

app/views/team_members/add_permanent_position.js.erb
'<%= form_for(@team_member) do |ff| %>'
  $('#permanent-positions').append('<%= escape_javascript(render partial: "permanent_position", locals: { f: ff }) %>');
'<% end %>'

app/views/team_members/edit.html.erb
<h1>Editing Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %> |
<%= link_to 'Destroy', @team_member, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/team_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Members</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td>Name: </td>
        <td><%= "#{team_member.first_name} #{team_member.last_name}"%></td>
      </tr>
      <tr>
        <td>Employee Number:</td>
        <td><%= "#{team_member.employee_number}" %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Member', new_team_member_path %>

app/views/team_members/new.html.erb
<h1>New Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/remove_dates_unavailable.js.erb
$('#<%= @id %>').remove();

app/views/team_members/remove_permanent_position.js.erb
$('#<%= @id %>').remove();

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

Name: <%= "#{@team_member.first_name} #{@team_member.last_name}"  %><br />
Employee Number: <%= "#{@team_member.employee_number}" %><br />

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %> |
<%= link_to 'Destroy', @team_member, method: :delete, data: { confirm: 'Are you sure?' } %>