config/routes.rb
Rails.application.routes.draw do


  resources :responsibilities
  resources :setups
  resources :sorts
  resources :sort_types
  resources :rosters
  devise_for :users
  resources :schedules
  resources :team_members
  resources :positions

  root to: "home#index"

  get '/dashboard', to: "home#dashboard", as: 'dashboard'
  get '/employees', to: "team_members#index", as: 'employees'

  get "/add_dates_unavailable/", to: 'team_members#add_dates_unavailable', as: 'add_dates_unavailable'
  get "/remove_dates_unavailable/:id", to: 'team_members#remove_dates_unavailable', as: 'remove_dates_unavailable'

  get "/add_permanent_position", to: 'team_members#add_permanent_position', as: 'add_permanent_position'
  get "/remove_permanent_position/:id", to: 'team_members#remove_permanent_position', as: 'remove_permanent_position'

end

app/models/responsibility.rb
class Responsibility < ApplicationRecord
  belongs_to :sort
  belongs_to :team_member, optional: true
  belongs_to :position

end

app/controllers/responsibilities_controller.rb
class ResponsibilitiesController < ApplicationController
  before_action :set_responsibility, only: [:show, :edit, :update, :destroy]

  # GET /responsibilities
  # GET /responsibilities.json
  def index
    @responsibilities = Responsibility.all
  end

  # GET /responsibilities/1
  # GET /responsibilities/1.json
  def show
  end

  # GET /responsibilities/new
  def new
    @responsibility = Responsibility.new
  end

  # GET /responsibilities/1/edit
  def edit
  end

  # POST /responsibilities
  # POST /responsibilities.json
  def create
    @responsibility = Responsibility.new(responsibility_params)

    respond_to do |format|
      if @responsibility.save
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully created.' }
        format.json { render :show, status: :created, location: @responsibility }
      else
        format.html { render :new }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibilities/1
  # PATCH/PUT /responsibilities/1.json
  def update
    respond_to do |format|
      if @responsibility.update(responsibility_params)
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsibility }
      else
        format.html { render :edit }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibilities/1
  # DELETE /responsibilities/1.json
  def destroy
    @responsibility.destroy
    respond_to do |format|
      format.html { redirect_to responsibilities_url, notice: 'Responsibility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsibility
      @responsibility = Responsibility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responsibility_params
      params.fetch(:responsibility, {})
    end
end

app/helpers/responsibilities_helper.rb
module ResponsibilitiesHelper
end

app/views/responsibilities/_form.html.erb
<%= form_for(responsibility) do |f| %>
  <% if responsibility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(responsibility.errors.count, "error") %> prohibited this responsibility from being saved:</h2>

      <ul>
      <% responsibility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responsibilities/edit.html.erb
<h1>Editing Responsibility</h1>

<%= render 'form', responsibility: @responsibility %>

<%= link_to 'Show', @responsibility %> |
<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responsibilities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibilities.each do |responsibility| %>
      <tr>
        <td><%= link_to 'Show', responsibility %></td>
        <td><%= link_to 'Edit', edit_responsibility_path(responsibility) %></td>
        <td><%= link_to 'Destroy', responsibility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsibility', new_responsibility_path %>

app/views/responsibilities/new.html.erb
<h1>New Responsibility</h1>

<%= render 'form', responsibility: @responsibility %>

<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_responsibility_path(@responsibility) %> |
<%= link_to 'Back', responsibilities_path %>